# Generated by Django 5.0 on 2024-01-22 18:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('topics', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='topic',
            name='image',
            field=models.ImageField(default='default-post.jpg', upload_to='topic_pics'),
        ),
    ]
