# Generated by Django 5.0 on 2024-01-25 06:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('topics', '0002_alter_topic_image'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='topic',
            options={'ordering': ['-updated', '-published_at']},
        ),
        migrations.AddField(
            model_name='topic',
            name='updated',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='topic',
            name='image',
            field=models.ImageField(upload_to='topic_pics'),
        ),
    ]
