# Generated by Django 5.0 on 2024-01-25 12:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('topics', '0003_alter_topic_options_topic_updated_alter_topic_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.AlterModelOptions(
            name='topic',
            options={},
        ),
        migrations.RemoveField(
            model_name='topic',
            name='updated',
        ),
        migrations.AlterField(
            model_name='topic',
            name='image',
            field=models.ImageField(default='default-post.jpg', upload_to='topic_pics'),
        ),
        migrations.AddField(
            model_name='topic',
            name='categories',
            field=models.ManyToManyField(to='topics.category'),
        ),
    ]
