# Generated by Django 5.0 on 2024-01-30 06:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('topics', '0006_alter_comment_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='topic',
            name='is_featured',
            field=models.BooleanField(default=False),
        ),
    ]
