# Generated by Django 5.0 on 2024-01-30 07:54

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('topics', '0007_topic_is_featured'),
    ]

    operations = [
        migrations.AlterField(
            model_name='topic',
            name='content',
            field=ckeditor.fields.RichTextField(blank=True, null=True),
        ),
    ]
