# Generated by Django 5.0 on 2024-01-30 08:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('topics', '0008_alter_topic_content'),
    ]

    operations = [
        migrations.AlterField(
            model_name='topic',
            name='content',
            field=models.TextField(blank=True, null=True),
        ),
    ]
