# Generated by Django 5.0 on 2024-01-30 08:26

import tinymce.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('topics', '0009_alter_topic_content'),
    ]

    operations = [
        migrations.AlterField(
            model_name='topic',
            name='content',
            field=tinymce.models.HTMLField(blank=True, null=True),
        ),
    ]
